=== alinalihassan/dotbash/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "defaults": {
      "default": {
        "link": {
          "create": false,
          "relink": false,
          "force": false
        },
        "shell": {
          "quiet": false
        }
      },
      "type": "object",
      "properties": {
        "link": {
          "default": {
            "create": false,
            "relink": false,
            "force": false
          },
          "type": "object",
          "properties": {
            "create": {
              "default": false,
              "type": "boolean"
            },
            "relink": {
              "default": false,
              "type": "boolean"
            },
            "force": {
              "default": false,
              "type": "boolean"
            }
          },
          "required": [],
          "additionalProperties": false
        },
        "shell": {
          "default": {
            "quiet": false
          },
          "type": "object",
          "properties": {
            "quiet": {
              "default": false,
              "type": "boolean"
            }
          },
          "required": [],
          "additionalProperties": false
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "link": {
      "default": {},
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {
        "type": "string"
      }
    },
    "shell": {
      "default": [],
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "command": {
            "type": "string"
          },
          "quiet": {
            "default": false,
            "type": "boolean"
          }
        },
        "required": [
          "command"
        ],
        "additionalProperties": false
      }
    },
    "packageManager": {
      "default": {
        "installSelf": true,
        "dependenciesFile": ""
      },
      "type": "object",
      "properties": {
        "installSelf": {
          "default": true,
          "type": "boolean"
        },
        "dependenciesFile": {
          "default": "",
          "type": "string"
        }
      },
      "required": [],
      "additionalProperties": false
    }
  },
  "required": [],
  "additionalProperties": false
}

=== alinalihassan/dotbash/dotbash.json
{
  "defaults": {
    "link": {
      "relink": true,
      "force": true,
      "create": true
    }
  },
  "link": {
    "~/.gitconfig": "git/.gitconfig",
    "~/.gitignore_global": "git/.gitignore_global",
    "~/.config/nvim": "nvim",
    "~/.config/fish": "fish",
    "~/.config/bat": "bat",
    "~/.config/ghostty": "ghostty",
    "~/.config/opencode/opencode.jsonc": "opencode/opencode.jsonc",
    "~/Library/Application Support/lazygit/config.yml": "lazygit/config.yml"
  },
  "packageManager": {
    "installSelf": true,
    "dependenciesFile": "brew/Brewfile"
  },
  "shell": [
    {
      "description": "Set Fish as default shell",
      "command": "chsh -s $(which fish)"
    },
    {
      "description": "Install Fish Plugins",
      "command": "fish -c \"fisher update\""
    }
  ]
}
